import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#f95630",
        "on-secondary-container": "#6a3c00",
        "on-tertiary-container": "#00534d",
        "secondary-dim": "#764400",
        "tertiary-container": "#7fe6db",
        outline: "#747776",
        tertiary: "#006760",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#4f2c00",
        "tertiary-dim": "#005a54",
        "primary-dim": "#025d16",
        "on-primary-container": "#005c15",
        "on-surface-variant": "#595c5b",
        "on-surface": "#2c2f2e",
        "outline-variant": "#abaeac",
        "on-tertiary-fixed": "#003e39",
        "inverse-primary": "#9df197",
        "surface-bright": "#f5f7f5",
        "on-primary": "#d1ffc8",
        "primary-fixed-dim": "#90e28a",
        primary: "#176a21",
        "secondary-container": "#ffc791",
        "tertiary-fixed-dim": "#71d7cd",
        "secondary-fixed": "#ffc791",
        "surface-container": "#e6e9e7",
        "surface-container-high": "#e0e3e1",
        "inverse-surface": "#0b0f0e",
        "on-background": "#2c2f2e",
        surface: "#f5f7f5",
        "on-error-container": "#520c00",
        "secondary-fixed-dim": "#ffb467",
        "on-tertiary-fixed-variant": "#005d57",
        background: "#f5f7f5",
        "on-primary-fixed-variant": "#12661e",
        "primary-container": "#9df197",
        error: "#b02500",
        "tertiary-fixed": "#7fe6db",
        "primary-fixed": "#9df197",
        "surface-variant": "#d9dedb",
        "on-primary-fixed": "#00460e",
        "on-secondary": "#fff0e5",
        "on-tertiary": "#bffff7",
        "inverse-on-surface": "#9b9d9c",
        "surface-container-highest": "#d9dedb",
        "on-error": "#ffefec",
        secondary: "#874e00",
        "surface-container-low": "#eff1ef",
        "error-dim": "#b92902",
        "surface-tint": "#176a21",
        "on-secondary-fixed-variant": "#774400",
        "surface-dim": "#d1d5d3",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
